name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkoutmaster
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: zlx01/vuepress-deploy2
          TARGET_BRANCH: master
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: src/.vuepress/dist
#          CNAME: https://www.xxx.com
